	.align 2
gText_ConfirmSave::
	.string "Möchtest du das Spiel speichern?$"

gText_AlreadySavedFile::
	.string "There is already a saved file.\n"
	.string "Is it okay to overwrite it?$"

gText_SavingDontTurnOff::
	.string "SPEICHERN…\n"
	.string "BITTE DAS GERÄT NICHT AUSCHALTEN!$"

gText_PlayerSavedGame::
	.string "{PLAYER} hat das Spiel gespeichert.$"

gText_DifferentSaveFile::
	.string "ACHTUNG!\p"
	.string "Es gibt bereits einen Spielstand.\p"
	.string "Wenn jetzt gespeichert wird, geht\n"
	.string "der andere Spielstand mit allen\l"
	.string "Items und POKéMON für immer.\l"
	.string "verloren.\l"
	.string "Bist du sicher, dass du sichen\l"
	.string "und den anderen Spielstand\l"
	.string "überschreiben möchtest?$"

gText_SaveError::
	.string "Save error.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "SPEICHERN…\n"
	.string "BITTE DAS GERÄT NICHT AUSCHALTEN!$"
